### ISSUE TITLE
Wrong module name

### ISSUE THREAD

**Issue by marchrius** [alexjoffroy/angular-loaders#1]
The module name to include is "the-cormoran.loaderscss" and not "the-cormoran.angular-loaders".

Am I wrong? With "the-cormoran.angular-loaders" it tells me some errors.

**Comment by PriyanshDwivedi** [comment]
@Marchrius It is giving me errors for both the module names.

**Comment by alexjoffroy** [comment]
@Marchrius @PriyanshDwivedi 

I do not use this package anymore, but I just try it in a CodePen.

The minified version does not work and I get an error in my console.

But the not-minified script works well. You can see the CodePen here:
https://codepen.io/cormoran/pen/qakWky

I will try to fix and update the package ASAP.

**Comment by alexjoffroy** [comment]
241db89b3d4c2e284759d0a4bf61fe9aa1039076 fixes the bug.

Please refer to README.md for new installation and use instructions.

**Comment by mpint** [comment]
thanks for breaking my project by hardcoding your username into the module.  classy...

**Comment by alexjoffroy** [comment]
Even if I do not appreciate this kind of whiny comments, here are some explanations.

The project needed some structure improvements, and had not yet been released. And as my github nickname changed since the start of this project, I updated it in the module to be more consistent. 

So, yes, this (first) release breaks existing projects using angular-loaders. The next bugfixes/evolutions will be shipped in new releases, so this case should not arrive anymore.
